/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


package at.srfg.kmt.ehealth.phrs.security.model;


import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Generic representation for an user.
 *
 * @author Mihai
 */
@Entity
public class User implements Serializable {

    /**
     * Unique id, is generated by the underlying persistence layer.<br>
     * <b>Note : <b> Don't use this property in any kind of logic,
     * this property is used only by the underly persistence layer.
     */
    private Long id;

    /**
     * The user name.
     */
    private String name;

    /**
     * The user family name.
     */
    private String familyName;

    /**
     * The unique general accepted user identifier.
     */
    private String url;

    /**
     * Extra user information in any possible serializable format.
     */
    private Serializable original;

    /**
     * Builds an <code>User</code> instance.
     */
    public User() {
        // UNIMPLEMEMENTED
    }

    /**
     * Returns the family name for this user.
     * 
     * @return the family name for this user.
     */
    public String getFamilyName() {
        return familyName;
    }

    /**
     * Returns the unique id for this User instance. <br>
     * <b>Note : <b> Don't use this property in any kind of logic,
     * this property is used only by the underly persistence layer.
     *
     * @return the unique id for this user.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getId() {
        return id;
    }

    /**
     * Returns the name for this user.
     *
     * @return the name for this user.
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the extra information for this user in serializable format.
     *
     * @return the extra information for this user.
     */
    public Serializable getOriginal() {
        return original;
    }

    /**
     * Returns the unique general accepted user identifier.
     *
     * @return  the unique general accepted user identifier.
     */
    public String getUrl() {
        return url;
    }

    /**
     * Registers a new family name for this user.
     *
     * @param familyName the new family name for this user.
     */
    public void setFamilyName(String familyName) {
        this.familyName = familyName;
    }

    /**
     * Registers a new unique id for this User instance.<br>
     * <b>Note : <b> Don't set this property by hand (using this
     * method) and don't use this property any kind of logic.
     * This property is used only by the underly persistence layer.
     *
     * @param id the new unique id.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Registers a new name for this User instance.
     *
     * @param name the new name.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Registers a new extra user information for this User instance.
     * The extra user information can be everything
     * (e.g. xml documents, JSON objects, etc).
     *
     * @param name the extra user information.
     */
    public void setOriginal(Serializable original) {
        this.original = original;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Returns a string representation for this User.
     * The string representation for this User looks like
     * this :
     * <ul>
     * <li> the String 'User{name='
     * <li> the name property
     * <li> the String ', familyName='
     * <li> the familyName property
     * <li> the String ', url='
     * <li> the url property
     * <li> the String '}'
     * </ul>
     *
     * @return a string representation for this Group.
     */
    @Override
    public String toString() {
        final String result =
                String.format("User{name=%s, familyName=,url=%s}", name, familyName, url);

        return result;
    }
}
