//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 04:13:06 PM EET 
//


package tr.com.srdc.icardea.consenteditor.model;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{model.consenteditor.srdc.com.tr}subjectElements"/>
 *         &lt;element ref="{model.consenteditor.srdc.com.tr}resourceElements"/>
 *         &lt;element ref="{model.consenteditor.srdc.com.tr}actionElements"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "subjectElements",
    "resourceElements",
    "actionElements"
})
@XmlRootElement(name = "consentRuleTarget")
@Entity(name = "ConsentRuleTarget")
@Table(name = "CONSENTRULETARGET")
@Inheritance(strategy = InheritanceType.JOINED)
public class ConsentRuleTarget
    implements Serializable, Equals, HashCode
{

    @XmlElement(required = true)
    protected SubjectElements subjectElements;
    @XmlElement(required = true)
    protected ResourceElements resourceElements;
    @XmlElement(required = true)
    protected ActionElements actionElements;
    @XmlTransient
    protected Long hjid;

    /**
     * Gets the value of the subjectElements property.
     * 
     * @return
     *     possible object is
     *     {@link SubjectElements }
     *     
     */
    @ManyToOne(targetEntity = SubjectElements.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SUBJECTELEMENTS_CONSENTRULET_0")
    public SubjectElements getSubjectElements() {
        return subjectElements;
    }

    /**
     * Sets the value of the subjectElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubjectElements }
     *     
     */
    public void setSubjectElements(SubjectElements value) {
        this.subjectElements = value;
    }

    /**
     * Gets the value of the resourceElements property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceElements }
     *     
     */
    @ManyToOne(targetEntity = ResourceElements.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "RESOURCEELEMENTS_CONSENTRULE_0")
    public ResourceElements getResourceElements() {
        return resourceElements;
    }

    /**
     * Sets the value of the resourceElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceElements }
     *     
     */
    public void setResourceElements(ResourceElements value) {
        this.resourceElements = value;
    }

    /**
     * Gets the value of the actionElements property.
     * 
     * @return
     *     possible object is
     *     {@link ActionElements }
     *     
     */
    @ManyToOne(targetEntity = ActionElements.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "ACTIONELEMENTS_CONSENTRULETA_0")
    public ActionElements getActionElements() {
        return actionElements;
    }

    /**
     * Sets the value of the actionElements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionElements }
     *     
     */
    public void setActionElements(ActionElements value) {
        this.actionElements = value;
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof ConsentRuleTarget)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ConsentRuleTarget that = ((ConsentRuleTarget) object);
        {
            SubjectElements lhsSubjectElements;
            lhsSubjectElements = this.getSubjectElements();
            SubjectElements rhsSubjectElements;
            rhsSubjectElements = that.getSubjectElements();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "subjectElements", lhsSubjectElements), LocatorUtils.property(thatLocator, "subjectElements", rhsSubjectElements), lhsSubjectElements, rhsSubjectElements)) {
                return false;
            }
        }
        {
            ResourceElements lhsResourceElements;
            lhsResourceElements = this.getResourceElements();
            ResourceElements rhsResourceElements;
            rhsResourceElements = that.getResourceElements();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "resourceElements", lhsResourceElements), LocatorUtils.property(thatLocator, "resourceElements", rhsResourceElements), lhsResourceElements, rhsResourceElements)) {
                return false;
            }
        }
        {
            ActionElements lhsActionElements;
            lhsActionElements = this.getActionElements();
            ActionElements rhsActionElements;
            rhsActionElements = that.getActionElements();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "actionElements", lhsActionElements), LocatorUtils.property(thatLocator, "actionElements", rhsActionElements), lhsActionElements, rhsActionElements)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            SubjectElements theSubjectElements;
            theSubjectElements = this.getSubjectElements();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "subjectElements", theSubjectElements), currentHashCode, theSubjectElements);
        }
        {
            ResourceElements theResourceElements;
            theResourceElements = this.getResourceElements();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "resourceElements", theResourceElements), currentHashCode, theResourceElements);
        }
        {
            ActionElements theActionElements;
            theActionElements = this.getActionElements();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "actionElements", theActionElements), currentHashCode, theActionElements);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
