//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 04:13:06 PM EET 
//


package tr.com.srdc.icardea.consenteditor.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tr.com.srdc.icardea.consenteditor.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tr.com.srdc.icardea.consenteditor.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActionElements }
     * 
     */
    public ActionElements createActionElements() {
        return new ActionElements();
    }

    /**
     * Create an instance of {@link SubjectElement }
     * 
     */
    public SubjectElement createSubjectElement() {
        return new SubjectElement();
    }

    /**
     * Create an instance of {@link SentEmailTo }
     * 
     */
    public SentEmailTo createSentEmailTo() {
        return new SentEmailTo();
    }

    /**
     * Create an instance of {@link Members }
     * 
     */
    public Members createMembers() {
        return new Members();
    }

    /**
     * Create an instance of {@link TimeConstraint }
     * 
     */
    public TimeConstraint createTimeConstraint() {
        return new TimeConstraint();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link ResourceElement }
     * 
     */
    public ResourceElement createResourceElement() {
        return new ResourceElement();
    }

    /**
     * Create an instance of {@link ConsentRule }
     * 
     */
    public ConsentRule createConsentRule() {
        return new ConsentRule();
    }

    /**
     * Create an instance of {@link Individual }
     * 
     */
    public Individual createIndividual() {
        return new Individual();
    }

    /**
     * Create an instance of {@link ResourceElements }
     * 
     */
    public ResourceElements createResourceElements() {
        return new ResourceElements();
    }

    /**
     * Create an instance of {@link Condition }
     * 
     */
    public Condition createCondition() {
        return new Condition();
    }

    /**
     * Create an instance of {@link ConsentRuleTarget }
     * 
     */
    public ConsentRuleTarget createConsentRuleTarget() {
        return new ConsentRuleTarget();
    }

    /**
     * Create an instance of {@link Obligation }
     * 
     */
    public Obligation createObligation() {
        return new Obligation();
    }

    /**
     * Create an instance of {@link ConsentDocumentMetaDataType }
     * 
     */
    public ConsentDocumentMetaDataType createConsentDocumentMetaDataType() {
        return new ConsentDocumentMetaDataType();
    }

    /**
     * Create an instance of {@link SubjectElements }
     * 
     */
    public SubjectElements createSubjectElements() {
        return new SubjectElements();
    }

    /**
     * Create an instance of {@link ConsentDocument }
     * 
     */
    public ConsentDocument createConsentDocument() {
        return new ConsentDocument();
    }

}
