//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 04:13:06 PM EET 
//


package tr.com.srdc.icardea.consenteditor.model;

import java.io.Serializable;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{model.consenteditor.srdc.com.tr}sentEmailTo"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sentEmailTo"
})
@XmlRootElement(name = "obligation")
@Entity(name = "Obligation")
@Table(name = "OBLIGATION")
@Inheritance(strategy = InheritanceType.JOINED)
public class Obligation
    implements Serializable, Equals, HashCode
{

    protected SentEmailTo sentEmailTo;
    @XmlTransient
    protected Long hjid;

    /**
     * Gets the value of the sentEmailTo property.
     * 
     * @return
     *     possible object is
     *     {@link SentEmailTo }
     *     
     */
    @ManyToOne(targetEntity = SentEmailTo.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "SENTEMAILTO_OBLIGATION_HJID")
    public SentEmailTo getSentEmailTo() {
        return sentEmailTo;
    }

    /**
     * Sets the value of the sentEmailTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SentEmailTo }
     *     
     */
    public void setSentEmailTo(SentEmailTo value) {
        this.sentEmailTo = value;
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Obligation)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Obligation that = ((Obligation) object);
        {
            SentEmailTo lhsSentEmailTo;
            lhsSentEmailTo = this.getSentEmailTo();
            SentEmailTo rhsSentEmailTo;
            rhsSentEmailTo = that.getSentEmailTo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "sentEmailTo", lhsSentEmailTo), LocatorUtils.property(thatLocator, "sentEmailTo", rhsSentEmailTo), lhsSentEmailTo, rhsSentEmailTo)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            SentEmailTo theSentEmailTo;
            theSentEmailTo = this.getSentEmailTo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "sentEmailTo", theSentEmailTo), currentHashCode, theSentEmailTo);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
