//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 04:13:06 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "model.consenteditor.srdc.com.tr", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package tr.com.srdc.icardea.consenteditor.model;
