//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 04:13:06 PM EET 
//


package tr.com.srdc.icardea.consenteditor.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.hyperjaxb3.item.ItemUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="to" type="{model.consenteditor.srdc.com.tr}emailAddress" maxOccurs="unbounded"/>
 *         &lt;element name="emailText" type="{model.consenteditor.srdc.com.tr}non_empty_string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "to",
    "emailText"
})
@XmlRootElement(name = "sentEmailTo")
@Entity(name = "SentEmailTo")
@Table(name = "SENTEMAILTO")
@Inheritance(strategy = InheritanceType.JOINED)
public class SentEmailTo
    implements Serializable, Equals, HashCode
{

    @XmlElement(required = true)
    protected List<String> to;
    @XmlElement(required = true)
    protected String emailText;
    @XmlTransient
    protected Long hjid;
    protected transient List<SentEmailToToItem> toItems;

    /**
     * Gets the value of the to property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the to property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Transient
    public List<String> getTo() {
        if (to == null) {
            to = new ArrayList<String>();
        }
        return this.to;
    }

    /**
     * 
     * 
     */
    public void setTo(List<String> to) {
        this.to = to;
    }

    /**
     * Gets the value of the emailText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "EMAILTEXT", length = 255)
    public String getEmailText() {
        return emailText;
    }

    /**
     * Sets the value of the emailText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailText(String value) {
        this.emailText = value;
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    @OneToMany(targetEntity = SentEmailToToItem.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "TOITEMS_SENTEMAILTO_HJID")
    public List<SentEmailToToItem> getToItems() {
        if (this.toItems == null) {
            this.toItems = new ArrayList<SentEmailToToItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.to)) {
            this.to = ItemUtils.wrap(this.to, this.toItems, SentEmailToToItem.class);
        }
        return this.toItems;
    }

    public void setToItems(List<SentEmailToToItem> value) {
        this.to = null;
        this.toItems = null;
        this.toItems = value;
        if (this.toItems == null) {
            this.toItems = new ArrayList<SentEmailToToItem>();
        }
        if (ItemUtils.shouldBeWrapped(this.to)) {
            this.to = ItemUtils.wrap(this.to, this.toItems, SentEmailToToItem.class);
        }
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof SentEmailTo)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final SentEmailTo that = ((SentEmailTo) object);
        {
            List<String> lhsTo;
            lhsTo = this.getTo();
            List<String> rhsTo;
            rhsTo = that.getTo();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "to", lhsTo), LocatorUtils.property(thatLocator, "to", rhsTo), lhsTo, rhsTo)) {
                return false;
            }
        }
        {
            String lhsEmailText;
            lhsEmailText = this.getEmailText();
            String rhsEmailText;
            rhsEmailText = that.getEmailText();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "emailText", lhsEmailText), LocatorUtils.property(thatLocator, "emailText", rhsEmailText), lhsEmailText, rhsEmailText)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            List<String> theTo;
            theTo = this.getTo();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "to", theTo), currentHashCode, theTo);
        }
        {
            String theEmailText;
            theEmailText = this.getEmailText();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "emailText", theEmailText), currentHashCode, theEmailText);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
