//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.23 at 04:13:06 PM EET 
//


package tr.com.srdc.icardea.consenteditor.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allowFrom" type="{model.consenteditor.srdc.com.tr}non_empty_string"/>
 *         &lt;element name="allowUntil" type="{model.consenteditor.srdc.com.tr}non_empty_string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "allowFrom",
    "allowUntil"
})
@XmlRootElement(name = "timeConstraint")
@Entity(name = "TimeConstraint")
@Table(name = "TIMECONSTRAINT")
@Inheritance(strategy = InheritanceType.JOINED)
public class TimeConstraint
    implements Serializable, Equals, HashCode
{

    @XmlElement(required = true)
    protected String allowFrom;
    @XmlElement(required = true)
    protected String allowUntil;
    @XmlTransient
    protected Long hjid;

    /**
     * Gets the value of the allowFrom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ALLOWFROM", length = 255)
    public String getAllowFrom() {
        return allowFrom;
    }

    /**
     * Sets the value of the allowFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowFrom(String value) {
        this.allowFrom = value;
    }

    /**
     * Gets the value of the allowUntil property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "ALLOWUNTIL", length = 255)
    public String getAllowUntil() {
        return allowUntil;
    }

    /**
     * Sets the value of the allowUntil property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowUntil(String value) {
        this.allowUntil = value;
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof TimeConstraint)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final TimeConstraint that = ((TimeConstraint) object);
        {
            String lhsAllowFrom;
            lhsAllowFrom = this.getAllowFrom();
            String rhsAllowFrom;
            rhsAllowFrom = that.getAllowFrom();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "allowFrom", lhsAllowFrom), LocatorUtils.property(thatLocator, "allowFrom", rhsAllowFrom), lhsAllowFrom, rhsAllowFrom)) {
                return false;
            }
        }
        {
            String lhsAllowUntil;
            lhsAllowUntil = this.getAllowUntil();
            String rhsAllowUntil;
            rhsAllowUntil = that.getAllowUntil();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "allowUntil", lhsAllowUntil), LocatorUtils.property(thatLocator, "allowUntil", rhsAllowUntil), lhsAllowUntil, rhsAllowUntil)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theAllowFrom;
            theAllowFrom = this.getAllowFrom();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "allowFrom", theAllowFrom), currentHashCode, theAllowFrom);
        }
        {
            String theAllowUntil;
            theAllowUntil = this.getAllowUntil();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "allowUntil", theAllowUntil), currentHashCode, theAllowUntil);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
